version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./docker-data/nginx.conf:/etc/nginx/nginx.conf
  api1:
    image: spring-boot-k8s
    ports:
      - "8080:8080"
    environment:
      APP_NAME: api-1
  api2:
    image: spring-boot-k8s
    ports:
      - "8081:8080"
    environment:
      APP_NAME: api-2
  api3:
    image: spring-boot-k8s
    ports:
      - "8082:8080"
    environment:
      APP_NAME: api-3